name: Automatic Update

on:
  push:
  #schedule:
  #  - cron: "0 0 * * 0" # Every Sunday at midnight UTC

jobs:
  autoupdate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install Python dependencies
      run: |
        python -m pip install requests
    - name: Set up Rustfmt
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - name: Codegen
      run: python codegen.py
    - name: Check for changes
      id: git_diff
      run: |
        echo "changes=$(git diff --quiet; echo $?)" >> $GITHUB_ENV
    - name: Bump patch version and create PR
      if: env.changes == '1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        current_version=$(grep '^version =' Cargo.toml | cut -d '"' -f2)
        IFS='.' read -r major minor patch <<< "$current_version"
        new_version="$major.$minor.$((patch + 1))"
        sed -i "s/^version = \"$current_version\"/version = \"$new_version\"/" Cargo.toml

        branch=autoupdate/$(date +%F)
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b $branch
        git add -u
        git commit -m "Bump version to $new_version"
        git push --set-upstream origin $branch

        gh pr create --title "$(date +%F): Bump version to $new_version" --body "Automatic update."
