name: Rust CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Test and verify MSRV
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust - Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy

    - name: Set up Rust - Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Clippy
      run: cargo clippy -- -Dwarnings

    - name: Test with all features
      run: cargo test --all-features

    - name: Test with no default features
      run: cargo test --no-default-features

    - name: Install cargo-msrv
      run: cargo binstall --no-confirm cargo-msrv

    - name: MSRV
      run: |
        cargo +nightly generate-lockfile -Z minimal-versions
        cargo msrv verify
